

<body id="top" class="oneo-no-sidebar oneo-fullwidth overlapping-menu">
<?php include_once("includes/header.php"); ?>    

        <div class="content-wrapper">
            <main role="main" class="main-content">
                <div class="mod_article  max-width-viewport block" id="article-33697">
                    <div class="mod_article_inner">
                        <div class="ce_ser_head_2 block">
                            
                            
                            <div class="serhead-main-headline">
                                <h1>SER Glossary</h1>
                            </div>
                        </div>
                    </div>
                </div>
       
    
    <div class="mod_article  max-width-viewport block" id="article-33698" style="margin-top: -50px;">
        <div class="mod_article_inner">
            <div class="centered-wrapper ce_rsce_oneo_centered_wrapper_start " style="margin-bottom: 50px; ">
                <div class="centered-wrapper-inner ">
                    <h4 class="text-center content-headline">These pages offer you information on the core topics of our
                        software &amp; services.</h4>
                    <div class="ce_rsce_ser_icon_boxes startseite block">
                        <section class="ce_rsce_ser_icon_boxes startseite">
                            <div class="ser-icon-boxes-container">
                                <a class="ser-icon-boxes-item icon-boxes-item  -inverted-icon " style=""
                                    href="/en/knowledge-center/glossary/what-is-enterprise-content-management.html">
                                    <div class="ser-icon-boxes-element icon-boxes-item  -inverted-icon " style="">
                                        <div class="ser-icon-boxes-element-inner icon-boxes-item  -inverted-icon "
                                            style="">
                                            <span class="icon-boxes-item-icon" style="" data-icon="&#xe929;"></span>
                                            <div class="ser-icon-boxes-description">
                                                <p class="-medium">What is ECM?</p>
                                                <div class="ser-icon-boxes-text">
                                                    <p>Definition, goals and benefits of an ECM solution.</p>
                                                </div>
                                                <p class="ser-icon-boxes-cta"><button
                                                        class="ser-icon-boxes-button button" title="Learn more">Learn
                                                        more</button></p>
                                            </div>
                                            <div class="ser-icon-boxes-more">»</div>
                                        </div>
                                    </div>
                                </a>
                                <a class="ser-icon-boxes-item icon-boxes-item  -inverted-icon " style=""
                                    href="/en/knowledge-center/glossary/what-is-business-process-management.html">
                                    <div class="ser-icon-boxes-element icon-boxes-item  -inverted-icon " style="">
                                        <div class="ser-icon-boxes-element-inner icon-boxes-item  -inverted-icon "
                                            style="">
                                            <span class="icon-boxes-item-icon" style="" data-icon="&#xe91f;"></span>
                                            <div class="ser-icon-boxes-description">
                                                <p class="-medium">What is BPM?</p>
                                                <div class="ser-icon-boxes-text">
                                                    <p>Business Process Management (BPM) to the point.</p>
                                                </div>
                                                <p class="ser-icon-boxes-cta"><button
                                                        class="ser-icon-boxes-button button" title="Learn more">Learn
                                                        more</button></p>
                                            </div>
                                            <div class="ser-icon-boxes-more">»</div>
                                        </div>
                                    </div>
                                </a>
                                <a class="ser-icon-boxes-item icon-boxes-item  -inverted-icon " style=""
                                    href="/en/knowledge-center/glossary/what-is-document-management.html">
                                    <div class="ser-icon-boxes-element icon-boxes-item  -inverted-icon " style="">
                                        <div class="ser-icon-boxes-element-inner icon-boxes-item  -inverted-icon "
                                            style="">
                                            <span class="icon-boxes-item-icon" style="" data-icon="&#xe929;"></span>
                                            <div class="ser-icon-boxes-description">
                                                <p class="-medium">What is DMS?</p>
                                                <div class="ser-icon-boxes-text">
                                                    <p>What does a document management system offer? &nbsp;</p>
                                                </div>
                                                <p class="ser-icon-boxes-cta"><button
                                                        class="ser-icon-boxes-button button" title="Learn more">Learn
                                                        more</button></p>
                                            </div>
                                            <div class="ser-icon-boxes-more">»</div>
                                        </div>
                                    </div>
                                </a>
                                <a class="ser-icon-boxes-item icon-boxes-item  -inverted-icon " style=""
                                    href="/en/knowledge-center/glossary/ap-automation-glossary.html">
                                    <div class="ser-icon-boxes-element icon-boxes-item  -inverted-icon " style="">
                                        <div class="ser-icon-boxes-element-inner icon-boxes-item  -inverted-icon "
                                            style="">
                                            <span class="icon-boxes-item-icon" style="" data-icon="&#xe044;"></span>
                                            <div class="ser-icon-boxes-description">
                                                <p class="-medium">AP automation</p>
                                                <div class="ser-icon-boxes-text">
                                                    <p>Digitizing invoices and automating the workflow, from data
                                                        capture through payment</p>
                                                </div>
                                                <p class="ser-icon-boxes-cta"><button
                                                        class="ser-icon-boxes-button button" title="Learn more">Learn
                                                        more</button></p>
                                            </div>
                                            <div class="ser-icon-boxes-more">»</div>
                                        </div>
                                    </div>
                                </a>
                                <a class="ser-icon-boxes-item icon-boxes-item  -inverted-icon " style=""
                                    href="/en/technology/intelligent-information-management.html">
                                    <div class="ser-icon-boxes-element icon-boxes-item  -inverted-icon " style="">
                                        <div class="ser-icon-boxes-element-inner icon-boxes-item  -inverted-icon "
                                            style="">
                                            <span class="icon-boxes-item-icon" style="" data-icon="&#xe959;"></span>
                                            <div class="ser-icon-boxes-description">
                                                <p class="-medium">Information Management</p>
                                                <div class="ser-icon-boxes-text">
                                                    <p>Definition &amp; Essentials around information management.</p>
                                                </div>
                                                <p class="ser-icon-boxes-cta"><button
                                                        class="ser-icon-boxes-button button" title="Learn more">Learn
                                                        more</button></p>
                                            </div>
                                            <div class="ser-icon-boxes-more">»</div>
                                        </div>
                                    </div>
                                </a>
                                <a class="ser-icon-boxes-item icon-boxes-item  -inverted-icon " style=""
                                    href="/en/knowledge-center/glossary/what-is-compliance-management.html">
                                    <div class="ser-icon-boxes-element icon-boxes-item  -inverted-icon " style="">
                                        <div class="ser-icon-boxes-element-inner icon-boxes-item  -inverted-icon "
                                            style="">
                                            <span class="icon-boxes-item-icon" style="" data-icon="&#xe960;"></span>
                                            <div class="ser-icon-boxes-description">
                                                <p class="-medium">Compliance Management</p>
                                                <div class="ser-icon-boxes-text">
                                                    <p>What requirements must compliance management meet?</p>
                                                </div>
                                                <p class="ser-icon-boxes-cta"><button
                                                        class="ser-icon-boxes-button button" title="Learn more">Learn
                                                        more</button></p>
                                            </div>
                                            <div class="ser-icon-boxes-more">»</div>
                                        </div>
                                    </div>
                                </a>
                                <a class="ser-icon-boxes-item icon-boxes-item  -inverted-icon " style=""
                                    href="/en/knowledge-center/glossary/what-is-automated-invoice-processing.html">
                                    <div class="ser-icon-boxes-element icon-boxes-item  -inverted-icon " style="">
                                        <div class="ser-icon-boxes-element-inner icon-boxes-item  -inverted-icon "
                                            style="">
                                            <span class="icon-boxes-item-icon" style="" data-icon="&#xe93a;"></span>
                                            <div class="ser-icon-boxes-description">
                                                <p class="-medium">Invoice Verification</p>
                                                <div class="ser-icon-boxes-text">
                                                    <p>Advantages &amp; Electronic invoice verification capabilities.
                                                    </p>
                                                </div>
                                                <p class="ser-icon-boxes-cta"><button
                                                        class="ser-icon-boxes-button button" title="Learn more">Learn
                                                        more</button></p>
                                            </div>
                                            <div class="ser-icon-boxes-more">»</div>
                                        </div>
                                    </div>
                                </a>
                                <a class="ser-icon-boxes-item icon-boxes-item  -inverted-icon " style=""
                                    href="/en/knowledge-center/glossary/what-is-digital-archiving.html">
                                    <div class="ser-icon-boxes-element icon-boxes-item  -inverted-icon " style="">
                                        <div class="ser-icon-boxes-element-inner icon-boxes-item  -inverted-icon "
                                            style="">
                                            <span class="icon-boxes-item-icon" style="" data-icon="&#xe938;"></span>
                                            <div class="ser-icon-boxes-description">
                                                <p class="-medium">Digital Archiving</p>
                                                <div class="ser-icon-boxes-text">
                                                    <p>Archiving of documents - more than a compulsory task.</p>
                                                </div>
                                                <p class="ser-icon-boxes-cta"><button
                                                        class="ser-icon-boxes-button button" title="Learn more">Learn
                                                        more</button></p>
                                            </div>
                                            <div class="ser-icon-boxes-more">»</div>
                                        </div>
                                    </div>
                                </a>
                                <a class="ser-icon-boxes-item icon-boxes-item  -inverted-icon " style=""
                                    href="/en/knowledge-center/glossary/what-is-a-workflow.html">
                                    <div class="ser-icon-boxes-element icon-boxes-item  -inverted-icon " style="">
                                        <div class="ser-icon-boxes-element-inner icon-boxes-item  -inverted-icon "
                                            style="">
                                            <span class="icon-boxes-item-icon" style="" data-icon="&#xe91f;"></span>
                                            <div class="ser-icon-boxes-description">
                                                <p class="-medium">Workflows</p>
                                                <div class="ser-icon-boxes-text">
                                                    <p>Agile workflow management with enterprise content management.</p>
                                                </div>
                                                <p class="ser-icon-boxes-cta"><button
                                                        class="ser-icon-boxes-button button" title="Learn more">Learn
                                                        more</button></p>
                                            </div>
                                            <div class="ser-icon-boxes-more">»</div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
 </div>
    </main>
    </div>
    </div>
    <script src="https://cdn.sergroup.com/assets/colorbox/js/colorbox.min.js?v=1.6.6"></script>
    <script>
        jQuery(function($) {
            $('a[data-lightbox]').map(function() {
                $(this).colorbox({
                    loop: !1,
                    rel: $(this).attr('data-lightbox'),
                    maxWidth: '95%',
                    maxHeight: '95%'
                })
            })
        })
    </script>
    <script src="files/frontend/js/ser-head-2.min.js?v=dd81ec3d" defer></script>
    <script src="files/frontend/js/sticky-form.min.js?v=dd81ec3d" defer></script>
    <script src="files/frontend/js/language-switcher-overlay.min.js?v=dd81ec3d" defer></script><noscript><iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-MR5QNLN" height="0" width="0"
            style="display:none;visibility:hidden"></iframe></noscript>
    <script src="files/frontend/js/gallery.min.js?v=dd81ec3d" defer></script>
    <script src="files/frontend/js/form.min.js?v=75424d59" defer></script>
    <script src="files/frontend/js/timezone-to-country.min.js?v=be10ee49" defer></script>
    <script src="https://cdn.sergroup.com/files/oneo/js/script-new.min.js?v=4"></script>
    <script type="application/ld+json">
        {
            "@context": "https:\/\/schema.org",
            "@graph": [{
                "@type": "WebPage"
            }]
        }
    </script>
    <script type="application/ld+json">
        {
            "@context": "https:\/\/schema.contao.org",
            "@graph": [{
                "@type": "Page",
                "fePreview": false,
                "groups": [],
                "noSearch": false,
                "pageId": 4428,
                "protected": false,
                "title": "Glossary"
            }]
        }
    </script>
    <?php include_once("includes/footer.php"); ?>
</body>
