<?php include_once("includes/header.php"); ?>

<style>
      /* Gradient text styling */
      .gradient {
        background: linear-gradient(331deg, #0090f9 0%, #00b09c 100%);
        /* -webkit-background-clip: text; */
        color: transparent;
        /* font-size: 250%; */
    }

    .terms-conditions {
        max-width: 900px;
        margin: auto;
        padding: 30px;
        background: #ffffff;
        border-radius: 10px;
        box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        /* font-family: Arial, sans-serif; */
        color: #333;
        line-height: 1.8;
    }

    .terms-conditions h1 {
        /* color: #0073e6; */
        text-align: center;
        font-size: 2rem;
        font-weight: bold;
    }

    .terms-conditions h2 {
        /* color: #0056b3; */
        text-align: left;
        font-size: 1.5rem;
        margin-top: 20px;
        font-weight: bold;
    }

    .terms-conditions p {
        text-align: justify;
        font-size: 1.1rem;
    }

    .terms-conditions ul {
        list-style-type: disc;
        padding-left: 20px;
    }
</style>

<div class="content-wrapper container my-5">
    <main role="main" class="main-content">
        <section class="terms-conditions bg-light p-4">
            <h1><span class="gradient">Terms & Conditions</span></h1>
            <p>Welcome to SmartIDP. By using our platform, you agree to abide by the following terms and conditions that govern our services.</p>

            <h2><span class="gradient">1. Introduction</span></h2>
            <p>This document is an electronic record in accordance with the Information Technology Act, 2000, and applicable rules. This electronic record is generated by a computer system and does not require physical or digital signatures.</p>
            <p>By accessing or using the services provided by SmartIDP, you are agreeing to the terms outlined below. If you do not agree with these terms, please refrain from using our platform.</p>

            <h2><span class="gradient">2. Platform Ownership</span></h2>
            <p>The platform is owned and operated by SmartIDP. By using the platform, you acknowledge and agree that you are contracting with SmartIDP, and the terms outlined here govern your use of the services provided.</p>

            <h2><span class="gradient">3. User Responsibilities</span></h2>
            <p>Users must ensure that any document uploaded complies with legal and ethical standards. Unauthorized use, data manipulation, or distribution of illegal content is strictly prohibited.</p>
            <p>By accessing the platform, you agree to provide true, accurate, and complete information during and after registration. You are responsible for all actions conducted through your registered account on the platform. You agree to independently assess the services to ensure they meet your requirements.</p>

            <h2><span class="gradient">4. Use of Services</span></h2>
            <p>You agree to use the platform and services in accordance with applicable laws and regulations. We do not guarantee the accuracy, performance, completeness, or suitability of the services or content provided on the platform. You are solely responsible for any risks associated with using the services.</p>

            <h2><span class="gradient">5. Intellectual Property</span></h2>
            <p>All trademarks, software, and content on SmartIDP are owned by us or our licensors. Unauthorized use or duplication is strictly prohibited.</p>

            <h2><span class="gradient">6. Service Availability</span></h2>
            <p>SmartIDP aims for 99.9% uptime but does not guarantee uninterrupted service. Scheduled maintenance or unforeseen technical issues may lead to temporary downtimes.</p>

            <h2><span class="gradient">7. Payment & Subscription</span></h2>
            <p>Certain features require a paid subscription. All payments are non-refundable except in cases specified in our refund policy.</p>

            <h2><span class="gradient">8. Cancellations and Refunds</span></h2>
            <p>Cancellation requests will only be considered if submitted within 2 days of purchasing the service. Cancellation will not be entertained if work has already begun or the service has been scheduled. If the service quality is unsatisfactory, you may request a rework or partial refund after evaluation. In case of technical issues, contact support within 2 days for investigation and resolution. Refunds, when approved, will be processed within 2 days of the request by SmartIDP.</p>

            <h2><span class="gradient">9. Limitation of Liability</span></h2>
            <p>SmartIDP shall not be liable for any inaccuracies, errors, or issues arising out of the use of services. You acknowledge that your use of services is entirely at your own risk.</p>
            <!-- <p>SmartIDP is not responsible for data loss, security breaches, or financial losses arising from the use of our services. You acknowledge that your use of services is entirely at your own risk.</p> -->

            <h2><span class="gradient">10. Force Majeure</span></h2>
            <p>SmartIDP shall not be held liable for any failure to perform its obligations if such failure is caused by factors beyond its control, such as natural disasters or unforeseen events.</p>

            <h2><span class="gradient">11. Dispute Resolution</span></h2>
            <p>These terms and conditions are governed by and construed in accordance with the laws of India. All disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts in Hyderabad, Telangana.</p>

            <h2><span class="gradient">12. Amendments to Terms</span></h2>
            <p>We reserve the right to modify these terms. Continued use of our services after updates signifies acceptance of the revised terms.</p>

            <h2><span class="gradient">13. Indemnification</span></h2>
            <p>You agree to indemnify and hold SmartIDP harmless from any claims, losses, or damages arising from your use of the platform or violation of these terms.</p>

            <h2><span class="gradient">14. Third-Party Links</span></h2>
            <p>Our platform may contain links to third-party websites. By clicking on these links, you agree to be bound by the terms and conditions of those websites. SmartIDP is not responsible for the content or services provided by these third parties.</p>

            <h2><span class="gradient">15. Contact Information</span></h2>
            <p>If you have any questions or concerns regarding these terms, please contact SmartIDP Customer Service at:</p>
            <a href="mailto:info@smartidp.ai.com">info@smartidp.ai.com</a>
        </section>
    </main>
</div>

<?php include_once("includes/footer.php"); ?>